/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { forwardRef, useRef } from 'react'

import {useGLTF,Center,Text3D,Torus ,Box, CurveModifier , Plane} from '@react-three/drei'

import FakeGlowMaterial from '../utils/FakeGlowMaterial.jsx'





export default forwardRef((props , ref) => {
  const { nodes, materials } = useGLTF('logoforum1.glb')
  console.log(nodes)
  const modelMaterial = nodes.Plane.material
  // const torus1ref = useRef()
  // const torus2ref = useRef()
  // const torus3ref = useRef()
  // const path1 = getRandomPointsOnRing(2.1,0.1)
    


//   const handlePos = [
//     new THREE.Vector3( -1, 0, 1 ),
//     new THREE.Vector3( -5, 5, 5 ),
//     new THREE.Vector3( 0, 0, 0 ),
//     new THREE.Vector3( 5, -5, 5 ),
//     new THREE.Vector3( 1, 0, 1 )
//   ]

// const curveRef = useRef()
// const curve = React.useMemo(() => new THREE.CatmullRomCurve3([...path1], true, 'centripetal'), [path1])


  const { ...config } = {
    color: 0xFFFFFF,        // Blue-ish color
    // color: 0x0000AA,        // Blue-ish color

    // emissive: 0x072534,     // Dark green emissive color
    // specular: 0xff0000,     // Grey specular highlight
    // shininess: 100,         // Shininess of the material
    // flatShading: false,      // Flat shading mode
    // side: THREE.DoubleSide, // Render both sides of the material
    // wireframe: true,       // Whether to render as wireframe
    // opacity: .9,             // Material opacity (1 means fully opaque)
    // transparent: false,     // Whether material can be transparent
    // reflectivity: 0.8,      // Reflectivity of the material (affects mirror-like reflection)
    // depthTest: true,        // Test for z-ordering
    // depthWrite: true,
    // wireframe: true
  }

  const {...HoloProps} = {
  fresnelAmount: 0.65,
  fresnelOpacity: 0.2,
  scanlineSize: 9.0,
  hologramBrightness: 3.2,
  signalSpeed: 3.15,
  hologramColor: "#51a4de",
  enableBlinking: false,
  enabled: true,

  }


  return (
    <group ref={ref}>
      <group position={[0, 2, 0]}  {...props} dispose={null} >
        <Center>

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane.geometry}
            // material={nodes.Plane.material}
            scale={[2, 2, 2]}

          >
            <meshBasicMaterial color="#FFFFFF" /> The color will appear without the need for lights
            {/* <HolographicMaterial {...HoloProps}/> */}
          </mesh>






        </Center>

      </group>

      <group position={[0, -0.7, 0]} rotation={[0, 0, 0]}>
        <Center>
          <Text3D
            color="#0000FF"
            anchorX="center"
            anchorY="middle"
            fontSize={2}
            font={"/fonts/Overpass_Bold.json"}
            bevelEnabled
            bevelSize={.003}
            bevelSegments={10}
            curveSegments={10}
            bevelThickness={0.001}
            scale={[0.9, 0.9, 0.9]}





          >
            X-Ops Space Forum
            {/* <meshBasicMaterial {...config} /> */}
            <FakeGlowMaterial
              falloff={0.9}
              glowInternalRadius={1.7}
              glowColor={"#ffffff"}
              glowSharpness={2.3}
              side={"THREE.DoubleSide"}
              opacity={1.0}
              depthTest={false} />

            {/* <HolographicMaterial {...HoloProps}/> */}


          </Text3D>
        </Center>

      </group>
      <group position={[0, -1.7, 0]} rotation={[0, 0, 0]}>
        <Center>
          <Text3D
            color="#FFFFFF"
            anchorX="center"
            anchorY="middle"
            fontSize={2}
            font={"/fonts/Overpass_Bold.json"}
            bevelEnabled
            bevelSize={.003}
            bevelSegments={10}
            curveSegments={10}
            bevelThickness={0.01}
            scale={[0.5, 0.5, 0.5]}





          >
            Exploring ML, Development and Security Galaxies
            <meshBasicMaterial {...config} />
            {/* <HolographicMaterial {...HoloProps}/> */}
            <FakeGlowMaterial
              falloff={1.2}
              glowInternalRadius={1.7}
              glowColor={"#ffffff"}
              glowSharpness={1.3}
              side={"THREE.BackSide"}
              opacity={1.0}
              depthTest={false} />

          </Text3D>

        </Center>

      </group>

    
      

    </group>
  )
}
)

useGLTF.preload('/supcomlogo-v1.glb')
