/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'  
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame } from '@react-three/fiber'


export function SupComLogo(props) {
  const { nodes, materials } = useGLTF('supcomlogo-v1.glb')
  console.log(nodes)
  const modelMaterial = nodes.Plane.material
  const supcomlogo = useRef()
  // useFrame(({ clock }) => {
  //   supcomlogo.current.position.y =Math.sin(2*clock.getElapsedTime())*0.1
  // })
  console.log(modelMaterial)
  return (
    <group {...props} dispose={null} ref={supcomlogo}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        // material={nodes.Plane.material}
        scale={[3.685, 1, 1.528]}
      >
        <meshBasicMaterial color="#ffffff" /> {/* The color will appear without the need for lights */}
        </mesh>

      

    </group>
  )
}

useGLTF.preload('/supcomlogo-v1.glb')